name: apptive_grid_heinzelmen
description: A collection of little helpers for Flutter Apps that use ApptiveGrid.
version: 0.4.0
homepage: https://www.apptivegrid.de
repository: https://github.com/zweidenker/flutter-heinzelmen/packages/apptive_grid_heinzelmen

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.15.0
  apptive_grid_user_management: ^0.4.0
  apptive_grid_theme: ^0.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  intl: ^0.17.0
  provider: ^6.0.3
  universal_file: ^1.0.0
  zweidenker_heinzelmen: ^0.0.2+1

dev_dependencies:
  alchemist: ^0.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1


flutter:
  uses-material-design: true
