name: apptive_grid_heinzelmen
description: A collection of little helpers for Flutter Apps that use ApptiveGrid.
version: 1.5.0
homepage: https://www.apptivegrid.de
repository: https://github.com/zweidenker/flutter-heinzelmen/packages/apptive_grid_heinzelmen

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^2.1.0
  apptive_grid_user_management: ^2.0.1
  apptive_grid_theme: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  http: '>=0.13.6 <2.0.0'
  intl: ^0.18.0
  provider: ^6.0.5
  universal_file: ^1.0.0
  zweidenker_heinzelmen: ^2.0.0

dev_dependencies:
  alchemist:
    git:
      url: https://github.com/abausg/alchemist
      ref: flutter-3-13
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.1
  mocktail_image_network: ^1.0.0


flutter:
  uses-material-design: true
