name: apptivegrid_toolbox
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^0.9.4
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.2

dev_dependencies:
  alchemist: ^0.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
