name: zweidenker_heinzelmen
description: A Flutter Package with useful helpers that are used across Flutter Apps by ZWEIDENKER
version: 2.0.0
homepage: https://www.zweidenker.de
repository: https://github.com/zweidenker/flutter-heinzelmen/packages/zweidenker_heinzelmen

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_tracking_transparency: ^2.0.4
  flutter:
    sdk: flutter
  flutter_web_browser: ^0.17.1
  package_info_plus: ^4.1.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mocktail: ^1.0.1
  plugin_platform_interface: ^2.1.6
  url_launcher_platform_interface: ^2.1.5

flutter:

